version: "3.9"
networks:
  my-network:
    driver: bridge
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db 
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=mydatabase
    networks:
      - my-network
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 1s
      timeout: 5s
      retries: 5
    command:
      - sh
      - -c
      - |
          sleep 5
          postgres -D /var/lib/postgresql/data
          psql -U postgres -c "CREATE DATABASE mydatabase;"
    networks:
      - my-network 