apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-rails-app-pipeline
spec:
  workspaces:
  - name: shared-workspace
  tasks:
  - name: fetch-repository
    taskRef:
      name: git-clone
      kind: Task
    workspaces:
    - name: output
      workspace: shared-workspace
    params:
    - name: url
      value: https://github.com/sansugupta/Budget-App.git
    - name: revision
      value: main
  - name: update-manifest
    runAfter:
      - fetch-repository
    workspaces:
    - name: source
      workspace: shared-workspace
    taskRef:
      name: update-manifest-task
  - name: sync-argocd
    runAfter:
      - update-manifest
    taskRef:
      name: sync-argocd-task
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest-task
spec:
  workspaces:
  - name: source
  steps:
  - name: update-image-tag
    image: ubuntu:latest
    workingDir: $(workspaces.source.path)
    command:
      - /bin/bash
    args:
      - -c  
      - |
        sed -i 's/my-rails-app.yaml/my-rails-app:latest/g' my-rails-app.yaml
        git config user.email "tekton@example.com"
        git config user.name "Tekton"
        git add my-rails-app.yaml
        git commit -m "Update image tag"
        git config credential.helper 'store --file=/etc/git-credentials'
        git push origin main
    volumeMounts:
    - name: git-credentials
      mountPath: /etc/git-credentials
  volumes:
  - name: git-credentials
    secret:
      secretName: git-credentials
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sync-argocd-task
spec:
  steps:
  - name: argocd-sync
    image: argoproj/argocd
    command:
      - /bin/bash
    args:
      - -c
      - |
        argocd app sync my-rails-app