apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: my-rails-app-run-1
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: my-rails-app-pipeline
  params:
  - name: url
    value: https://github.com/sansugupta/Budget-App.git
  - name: revision
    value: main
  serviceAccountName: dockerhub-service-account 
  workspaces:
  - name: shared-workspace
    persistentVolumeClaim:
      claimName: my-workspace-pvc